# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-11 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import golearnApp.gomodels.BaseTable


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('abbreviation', models.CharField(max_length=10)),
                ('stage', models.CharField(max_length=40)),
                ('logo', models.ImageField(upload_to=golearnApp.gomodels.BaseTable.get_image_path)),
                ('bio', models.TextField()),
                ('pupose', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('abbreviation', models.CharField(max_length=10)),
                ('teacher', models.CharField(max_length=40)),
                ('stage', models.IntegerField()),
                ('logo', models.ImageField(upload_to=golearnApp.gomodels.BaseTable.get_image_path)),
                ('bio', models.TextField()),
                ('time', models.TextField()),
                ('price', models.IntegerField()),
                ('rtmpaddr', models.CharField(max_length=40)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golearnApp.campus')),
            ],
        ),
        migrations.CreateModel(
            name='homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework', models.FileField(upload_to=golearnApp.gomodels.BaseTable.get_upfile_path)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golearnApp.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='students_classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golearnApp.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='teacher_classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golearnApp.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Ustudentinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('upasswd', models.CharField(max_length=40)),
                ('uemail', models.EmailField(max_length=40)),
                ('ubirth', models.DateField(max_length=40)),
                ('uimage', models.ImageField(upload_to=golearnApp.gomodels.BaseTable.get_image_path)),
                ('umoney', models.IntegerField()),
                ('usex', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('logo', models.ImageField(upload_to=golearnApp.gomodels.BaseTable.get_image_path)),
                ('addr', models.FileField(upload_to=golearnApp.gomodels.BaseTable.get_video_path)),
            ],
        ),
        migrations.CreateModel(
            name='Uteacherinfo',
            fields=[
                ('ustudentinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='golearnApp.Ustudentinfo')),
                ('uGo_credential', models.ImageField(upload_to=golearnApp.gomodels.BaseTable.get_image_path)),
                ('uTeach_credential', models.ImageField(upload_to=golearnApp.gomodels.BaseTable.get_image_path)),
                ('udescripition', models.TextField()),
            ],
            bases=('golearnApp.ustudentinfo',),
        ),
        migrations.AddField(
            model_name='students_classes',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golearnApp.Ustudentinfo'),
        ),
        migrations.AddField(
            model_name='teacher_classes',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golearnApp.Uteacherinfo'),
        ),
        migrations.AddField(
            model_name='campus',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='golearnApp.Uteacherinfo'),
        ),
    ]
